/**
 * Genre taxonomy constants for Bandcamp tag matching.
 * BC_GENRES: Bandcamp standard ~23 genre tags
 * DSP_GENRES: 64 DSP distribution genres (from spreadsheet)
 * SUB_GENRES: 692 sub-genres (from spreadsheet)
 */

export const BC_GENRES = [
  "rock",
  "electronic",
  "metal",
  "hip-hop-rap",
  "ambient",
  "punk",
  "folk",
  "pop",
  "classical",
  "country",
  "soundtrack",
  "world",
  "latin",
  "blues",
  "comedy",
  "spoken-word",
  "jazz",
  "experimental",
  "r-b-soul",
  "funk",
  "reggae",
  "acoustic",
  "alternative",
  "audiobooks",
  "podcasts",
] as const;

export const DSP_GENRES = [
  "African",
  "Alternative",
  "Ambient",
  "Arabic",
  "Argentinian",
  "Bluegrass",
  "Blues",
  "Brazilian",
  "Caribbean",
  "Children's",
  "Chinese",
  "Classical",
  "Comedy",
  "Country",
  "Dance",
  "Disco",
  "Electronic",
  "Flamenco",
  "Folk",
  "French",
  "Funk",
  "German",
  "Gospel",
  "Greek",
  "Hip-Hop / Rap",
  "Holiday",
  "Hungarian",
  "Indian",
  "Indie",
  "Israeli",
  "Italian",
  "Japanese",
  "Jazz",
  "J-Tracks",
  "Khaleeji",
  "Korean",
  "Laotian",
  "Latin",
  "Malian",
  "Metal",
  "Musica Mexicana",
  "New Age",
  "Noise & Non-Music Audio",
  "Opera",
  "Polish",
  "Pop",
  "Portuguese",
  "Punk",
  "R&B",
  "Reggae",
  "Regional Roots",
  "Religious",
  "Rock",
  "Romanian",
  "Russian",
  "Singer-Songwriter",
  "Soul",
  "Soundtrack",
  "Spoken Word",
  "Thai",
  "Turkish",
  "Uruguayan",
  "Vietnamese",
  "World",
] as const;

export const SUB_GENRES = [
  "Acid Jazz",
  "Acoustic",
  "Acoustic Blues",
  "Acoustic Country",
  "Acoustic Folk",
  "Acoustic Pop",
  "Acoustic Rock",
  "Acoustic Singer-Songwriter",
  "Acoustic Soul",
  "Adult Alternative",
  "Adult Contemporary",
  "African",
  "African Dancehall",
  "African Reggae",
  "Afrikaans",
  "Afro House",
  "Afro Soul",
  "Afrobeat",
  "Afro-Cuban Jazz",
  "Afro-folk",
  "Afro-fusion",
  "Afropop",
  "Album Rock",
  "Algerian Hip-Hop",
  "Alt-Country",
  "Alte",
  "Alternative",
  "Alternative Country",
  "Alternative Folk",
  "Alternative Hip-Hop",
  "Alternative Metal",
  "Alternative R&B",
  "Alternative Rap",
  "Alternative Rock",
  "Alt-Pop",
  "Amapiano",
  "Ambient",
  "Ambient Drone",
  "Ambient Folk",
  "Ambient House",
  "Ambient Noise",
  "Americana",
  "Appalachian",
  "Arab Indie",
  "Arab Pop",
  "Arab Trap",
  "Arabesk",
  "Arabic",
  "Arabic Hip-Hop",
  "Arabic Jazz",
  "Arabic Pop",
  "Argentinian Music",
  "Arrocha",
  "Art Song",
  "Asia",
  "ASMR",
  "Assamese",
  "Austropop",
  "Avant-Garde",
  "Axé",
  "Bachata",
  "Baile Funk",
  "Baladas y Boleros",
  "Ballroom / Vogue",
  "Baltimore Club",
  "Banda",
  "Baroque",
  "Basque Folk (Folk Vasco)",
  "Bass House",
  "Bassline",
  "Beats",
  "Bebop",
  "Bedroom Pop",
  "Benga",
  "Bengali",
  "Bhangra",
  "Bhojpuri",
  "Big Band",
  "Big Room",
  "Bikutsi",
  "Binaural Beats",
  "Black Metal",
  "Bluegrass",
  "Blues",
  "Blues Rock",
  "Blues Roots",
  "Blues Singer-Songwriter",
  "Bolero (Latin)",
  "Bolero (Vietnamese)",
  "Bollywood",
  "Bongo Flava",
  "Boogie Woogie",
  "Bossa Nova",
  "Brass & Woodwinds",
  "Brazilian Funk",
  "Brazilian Music",
  "Breakbeat",
  "Brega",
  "Britpop",
  "Bubblegum Pop",
  "Cajun",
  "Calypso",
  "Canadian Music",
  "Candombe",
  "Cantata",
  "Cantopop",
  "Caribbean",
  "Caribbean Music",
  "Carimbo",
  "Carnatic Classical",
  "Castilian Folk (Folk Castellano)",
  "Catalan Folk (Folk Catalan)",
  "CCM",
  "Celtic",
  "Celtic Folk",
  "Celtic Punk",
  "Chachacha",
  "Chamame",
  "Chamber Music",
  "Champeta",
  "Chanson Alternative",
  "Chanson Francaise",
  "Chanson Quebecois",
  "Chant",
  "Chicago Blues",
  "Chicha",
  "Children's Music",
  "Chill Beats",
  "Chill Pop",
  "Chillhop",
  "Chillstep",
  "Chillwave",
  "Chimurenga",
  "Chinese",
  "Chinese Alt",
  "Chinese Classical",
  "Chinese Flute",
  "Chinese Hip-Hop",
  "Chinese Opera",
  "Chinese Orchestral",
  "Chinese Regional Folk",
  "Chinese Rock",
  "Chinese Strings",
  "Choral",
  "Choro",
  "Christian Metal",
  "Christian Pop",
  "Christian Rap",
  "Christian Rock",
  "Christmas",
  "Christmas: Children's",
  "Christmas: Classic",
  "Christmas: Classical",
  "Christmas: Country",
  "Christmas: Jazz",
  "Christmas: Modern",
  "Christmas: Pop",
  "Christmas: R&B",
  "Christmas: Religious",
  "Christmas: Rock",
  "Chutney",
  "Classic Rock",
  "Classical",
  "Classical Crossover",
  "Classical Era",
  "Classical Piano",
  "Cloud Rap",
  "Club Music",
  "Comedy",
  "Conscious Hip-Hop",
  "Cool Jazz",
  "Corrido",
  "Country",
  "Country Blues",
  "Country Gospel",
  "Country Hip-Hop/Rap",
  "Country Quebecois",
  "Country Rap",
  "Country Rock",
  "Country Singer Songwriter",
  "Coupé-Décalé",
  "Crinkline (ASMR)",
  "Crunk",
  "Cuarteto",
  "Cuban",
  "Cumbia",
  "Dabke",
  "Dance",
  "Dance House",
  "Dance Pop",
  "Dancehall",
  "Dangdut",
  "Dansband",
  "Death Metal",
  "Deathcore",
  "Deep House",
  "Delta Blues",
  "Dembow",
  "Deutschpop",
  "Deutschrap",
  "Devotional & Spiritual",
  "Digital Maskandi",
  "Dini",
  "Dirty South",
  "Disco",
  "Disco Polo",
  "Dixieland",
  "Djent",
  "Doo Wop",
  "Downtempo",
  "Dreampop",
  "Drill",
  "Drum & Bass",
  "Dub",
  "Dubstep",
  "East Coast Hip-Hop",
  "East Coast Rap",
  "Easy Listening",
  "Eating (ASMR)",
  "Egyptian Hip-Hop",
  "Egyptian Pop",
  "Egyptian Tarab",
  "Electric Blues",
  "Electro",
  "Electro House",
  "Electro R&B",
  "Electro Shaabi",
  "Electro-Cha'abi",
  "Electronic",
  "Electronic Flamenco",
  "Electronic Gospel",
  "Electronica",
  "Electropop",
  "Emo",
  "Emo Rap",
  "Enka",
  "Entekhno",
  "Ethio Jazz",
  "Experimental Beats",
  "Experimental Jazz",
  "Experimental Rock",
  "Fado",
  "Faith",
  "Fantezi",
  "Farsi",
  "Fiction",
  "Filmi",
  "Flamenco",
  "Flamenco Chill",
  "Flamenco Jazz",
  "Flamenco Pop",
  "Folclor Andino",
  "Folclor Llanero",
  "Folclor Pacifico",
  "Folk",
  "Folk Blues",
  "Folk Metal",
  "Folk Pop",
  "Folk Punk",
  "Folk Quebecois",
  "Folk Rock",
  "Folk Singer-Songwriter",
  "Folklore Argentino",
  "Folklore Quebecois",
  "Folk-Rock",
  "Footwork",
  "Forró",
  "Free Jazz",
  "Freestyle",
  "French Indie Pop",
  "French Music",
  "French Pop",
  "Frevo",
  "Funk",
  "Funk Beats",
  "Funk Carioca",
  "Funk Rock",
  "Future Bass",
  "Future Funk",
  "Future House",
  "G House",
  "Gangsta Rap",
  "Garage",
  "Garage Rock",
  "Genge",
  "Gengetone",
  "German Folk",
  "German Music",
  "German Pop",
  "Ghanaian Drill",
  "Ghazals",
  "Glam Rock",
  "Gospel",
  "Gospel Blues",
  "Goth",
  "Gqom",
  "Greek Music",
  "Grime",
  "Grunge",
  "Guajira",
  "Guaracha",
  "Gujarati",
  "Hair Metal",
  "Hakka",
  "Halk",
  "Happy Hardcore",
  "Hard Bop",
  "Hard Rock",
  "Hardcore Punk",
  "Hardcore Rap",
  "Hardcore Techno",
  "Hardstyle",
  "Haryanvi",
  "Highlife",
  "Hill Country Blues",
  "Hindustani Classical",
  "Hip-Hop / Rap",
  "Holiday",
  "Honky Tonk",
  "Horror Punk",
  "Hörspiele",
  "House",
  "Huavno",
  "Hungarian Music",
  "Hymns",
  "Hyperpop",
  "Iberia",
  "IDM",
  "Impressionist",
  "Indian",
  "Indian Classical",
  "Indian Folk",
  "Indian Fusion",
  "Indian Indie",
  "Indian Music",
  "Indian Pop",
  "Indie",
  "Indo Pop",
  "Indonesian Religious",
  "Industrial",
  "Inspirational",
  "Iraqi Folk",
  "Iraqi Pop",
  "Iraqi Tarab",
  "Irish Traditional",
  "Islamic",
  "Israeli",
  "Israeli Music",
  "Italian Music",
  "J-Alternative",
  "Jam Band",
  "Jamgrass",
  "Japanese Music",
  "Jazz",
  "Jazz Beats",
  "Jazz Blues",
  "Jazz Funk",
  "Jazz Fusion",
  "Jazz Rap",
  "J-Dance/Electronic",
  "Jersey Club",
  "Jewish",
  "J-Hip Hop",
  "J-Pop",
  "J-R&B/Soul",
  "J-Rock",
  "J-Tracks",
  "Juke",
  "Jump Blues",
  "Jungle",
  "Kannada",
  "Kayokyoku",
  "Khaleeji",
  "Khaleeji Emirati",
  "Khaleeji Folk",
  "Khaleeji Hip-Hop",
  "Khaleeji Iraqi",
  "Khaleeji Jalsat",
  "Khaleeji Kuwaiti",
  "Khaleeji Pop",
  "Khaleeji Saudi",
  "Khaleeji Shailat",
  "Khaleeji Tarab",
  "Kindermusik",
  "Kizomba",
  "Klezmer",
  "Korean",
  "Korean Folk-Pop",
  "Korean Hip-Hop",
  "Korean Indie",
  "Korean Rock",
  "Korean Traditional",
  "K-Pop",
  "Krautrock",
  "Kuduro",
  "Kwaito",
  "Kwassa",
  "Laiko",
  "Laotian Music",
  "Latin",
  "Latin House",
  "Latin Jazz",
  "Latin Rap",
  "Latin Urban",
  "Levant",
  "Levant Electronic",
  "Levant Hip-Hop",
  "Levant Pop",
  "Liedermacher",
  "Liturgical",
  "Lo-Fi",
  "Lo-Fi Beats",
  "Lo-Fi Hip-Hop",
  "Lo-Fi House",
  "Lo-Fi Pop",
  "Lo-Fi Rock",
  "Louisiana Blues",
  "Lounge",
  "Lowercase",
  "Lullabies",
  "Maghreb Dance",
  "Maghreb Electronic",
  "Maghreb Hip-Hop",
  "Maghreb Indie",
  "Maghreb Pop",
  "Maghreb Rai",
  "Mahraganat",
  "Malayalam",
  "Malaysian Pop",
  "Malian Music",
  "Maloya",
  "Mambo",
  "Mandopop",
  "Manele",
  "Manilla Sound",
  "Mapouka",
  "Marathi",
  "Mariachi",
  "Maskandi",
  "Massage (ASMR)",
  "M'balax",
  "Mechanical (ASMR)",
  "Meditation",
  "Mediterranean",
  "Melodic House",
  "Meme Rap",
  "Merengue",
  "Metal",
  "Metalcore",
  "Miami Jook",
  "Minimal Techno",
  "minimalism",
  "Mizrahit",
  "Moomhahton",
  "Mor Lum",
  "Moroccan Hip-Hop",
  "Motswako",
  "MPB",
  "Mulatos",
  "Murga",
  "Musica Crista",
  "Musica Mexicana",
  "Musica Nativista",
  "Musica Popular Brasileira",
  "Musicals",
  "Native American Roots",
  "Nature",
  "N'Dombolo",
  "Neoclassical",
  "Neomelodico Napoletano",
  "Neo-Soul",
  "New Age",
  "New Orleans Bounce",
  "New Wave",
  "Noise & Non-Music Audio",
  "Nonfiction",
  "Norteno",
  "Nu Disco",
  "Nu-Metal",
  "Odia",
  "Old School Rap",
  "Opera",
  "OPM",
  "Oratorio",
  "Orchestral",
  "Original Pilipino Music",
  "Original Score",
  "Outlaw Country",
  "Outros (Brasil)",
  "Özgün",
  "Pagode",
  "Pagode Baiano",
  "Pentecostal",
  "Personal Attention (ASMR)",
  "Philly Club",
  "Physical Touch (ASMR)",
  "Pinoy Pop",
  "Pisadinha",
  "Poetry",
  "Polish Music",
  "Polka",
  "Pop",
  "Pop Country",
  "Pop Francaise",
  "Pop Funk",
  "Pop Leve",
  "Pop Punk",
  "Pop Quebecois",
  "Pop R&B",
  "Pop Rap",
  "Pop Rock",
  "Pop Singer-Songwriter",
  "Pop Urbaine",
  "Portuguese Music",
  "Post Bop",
  "Post-Punk",
  "Post-Rock",
  "Pow Wow",
  "Progressive House",
  "Progressive Metal",
  "Progressive Rock",
  "Psychedelic",
  "Psychedelic Electronic",
  "Psychobilly",
  "Psy-Trance",
  "Punjabi",
  "Punjabi Pop",
  "Punk",
  "Qawwali",
  "R&B",
  "R&B Quebecois",
  "Rabindra Sangeet",
  "Ragtime",
  "Rai",
  "Raices",
  "Rajasthani",
  "Rap",
  "Rap Napoletano",
  "Rap Quebecois",
  "Reggae",
  "Reggaeton",
  "Regional Indian",
  "Regional Mexicano",
  "Regional Roots",
  "Relaxation",
  "Religious",
  "Religious Music",
  "Renaissance",
  "Retro Rock",
  "Retro Soul",
  "Rock",
  "Rock & Roll",
  "Rock Quebecois",
  "Rock Singer-Songwriter",
  "Rockabilly",
  "Roleplay (ASMR)",
  "Romanian Music",
  "Romantic",
  "Rominimal",
  "Roots",
  "Roots Reggae",
  "Roots Rock",
  "Rumba (Congolese)",
  "Russian",
  "Russian Bard",
  "Russian Chanson",
  "Russian Hip-Hop",
  "Russian Music",
  "Russian Pop",
  "Russian Rock",
  "Russian Romance",
  "Salsa",
  "Salsa Choke",
  "Salsa y Tropical",
  "Samba",
  "Sanat",
  "Schlager",
  "Schweizer Mundart",
  "Sertanejo",
  "Shaaby",
  "Shamstep",
  "Shangaan Electro",
  "Sharqi",
  "Sheilat",
  "Shimmer Pop",
  "Shoegaze",
  "Shows",
  "Sierreno",
  "Singer-Songwriter",
  "Ska",
  "Skate Punk",
  "Slap House",
  "Slim (ASMR)",
  "Smooth Jazz",
  "Soca",
  "Soft Pop",
  "Soft Rock",
  "Son",
  "Sones",
  "Soukouss",
  "Soul",
  "Soul Funk",
  "Soul House",
  "Soul Pop",
  "Soul Singer-Songwriter",
  "Sound Effects",
  "Soundtrack",
  "South Africa",
  "South African Hip-Hop",
  "Southern Gospel",
  "Southern Rap",
  "Southern Rock",
  "Spiritual",
  "Spoken Word",
  "Standards",
  "Stoner Metal",
  "Stoner Rock",
  "String Orchestra",
  "Sufi",
  "Surf Rock",
  "Swing",
  "Symphonic Metal",
  "Symphony Orchestra",
  "Synthwave/Retrowave",
  "Taarab",
  "Tai-Pop",
  "Taiwanese Folk",
  "Taiwanese/Hokkien",
  "Tamil",
  "Tango",
  "Tapping (ASMR)",
  "Tarab",
  "Tech House",
  "Techno",
  "Tecnobrega",
  "Teen Pop",
  "Tejano",
  "Telugu",
  "Texas Blues",
  "Texas Country",
  "Tex-Mex",
  "Thai Country",
  "Thai Music",
  "Thai Pop",
  "Thrash Metal",
  "Tibetan Native Music",
  "Timba",
  "T-Pop",
  "Traditional Bluegrass",
  "Traditional Celtic",
  "Traditional Country",
  "Traditional Folk",
  "Traditional Gospel",
  "Traditional Pop",
  "Trance",
  "Trap",
  "Trap Beats",
  "Trap Latino",
  "Trapanele",
  "Tribal House",
  "Trip Hop",
  "Tropical House",
  "Trot",
  "Tunisian Hip-Hop",
  "Turkish",
  "Turkish Alternative",
  "Turkish Hip-Hop/Rap",
  "Turkish Music",
  "Turkish Pop",
  "Turkish Rock",
  "Turkish Trap Pop",
  "UK Funky",
  "UK Garage",
  "Urban Flamenco (Flamenco Urbano)",
  "Urdu",
  "Uruguayan Music",
  "Vallenato",
  "Vaporwave",
  "Variete Francaise",
  "Variete Urbaine",
  "Vietnamese Music",
  "Vocal Downtempo",
  "Vocal Jazz",
  "Vocal Pop",
  "Volksmusik",
  "West Coast Hip-Hop",
  "Whispering (ASMR)",
  "Worship",
  "Yoga",
  "Zouglou",
  "Zouk",
  "Zydeco",
] as const;

// Deterministic alias map: BC norm_name -> DSP genre display name
// Covers the 5 BC genres that do not exact-match any DSP genre
export const BC_TO_DSP_ALIASES: Record<string, string> = {
  "hip-hop-rap": "Hip-Hop / Rap",
  "r-b-soul": "R&B",
  "spoken-word": "Spoken Word",
  "experimental": "Alternative",
  "acoustic": "Folk",
};

// Pre-computed normalized Sets for O(1) lookup
function normalize(s: string): string {
  return s.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function normalizeTag(tag: string): string {
  return normalize(tag);
}

const BC_GENRES_SET = new Set(BC_GENRES.map(normalize));
const DSP_GENRES_SET = new Set(DSP_GENRES.map(normalize));
const DSP_GENRES_DISPLAY = new Map(DSP_GENRES.map(g => [normalize(g), g]));
const SUB_GENRES_SET = new Set(SUB_GENRES.map(normalize));
const SUB_GENRES_DISPLAY = new Map(SUB_GENRES.map(g => [normalize(g), g]));
const BC_ALIAS_NORMS = new Map(Object.entries(BC_TO_DSP_ALIASES).map(([k, v]) => [normalize(k), v]));

export interface TaxonomyMatch {
  bcGenre: string | null;
  dspGenre: string | null;
  subGenre: string | null;
}

export function matchTagToTaxonomy(tagNorms: string[]): TaxonomyMatch {
  let bcGenre: string | null = null;
  let dspGenre: string | null = null;
  let subGenre: string | null = null;

  for (const norm of tagNorms) {
    if (!bcGenre && BC_GENRES_SET.has(norm)) bcGenre = norm;
    if (!dspGenre) {
      if (DSP_GENRES_SET.has(norm)) dspGenre = DSP_GENRES_DISPLAY.get(norm) ?? norm;
      else if (BC_ALIAS_NORMS.has(norm)) dspGenre = BC_ALIAS_NORMS.get(norm) ?? null;
    }
    if (!subGenre && SUB_GENRES_SET.has(norm)) subGenre = SUB_GENRES_DISPLAY.get(norm) ?? norm;
    if (bcGenre && dspGenre && subGenre) break;
  }

  return { bcGenre, dspGenre, subGenre };
}
